### ISSUE TITLE
Dependency Graph of W3C Specs?

### ISSUE THREAD

**Issue by torgo** [w3ctag/meetings#12]
@tantek suggests: should we have a dependency graph of w3c specs' normative references? Would that help to inform the discussion on overall “architecture”? /cc @darobin #moderntooling

**Comment by darobin** [comment]
The systeam has made a beta version of its API available, which makes processing specs a _lot_ easier. I think that this would be an interesting project to carry out — do you have a time frame?

@tobie might also have things to bring to the table here.

**Comment by tobie** [comment]
Yup, working on a related solution but things have been delayed quite a bit due to my health issues. More on this soon.

**Comment by travisleithead** [comment]
@tobie just curious if this "dependency graph" is now a possibility using existing tools/APIs?

**Comment by darobin** [comment]
I don't believe that the APIs give you the references (which you need) but at least it allows you to list all specs. That's a helpful entry point, but the work involved in finding all the references (and distinguishing between normative and informative) is still manual.

**Comment by travisleithead** [comment]
OK. I think the TAG consensus is that we think it would be neat to have this capability, but if it doesn't happen that's not a big deal. Hypothetically, if we had such a graph, we are also not sure how useful it would be. Given all of that, our vote is to close the issue :) Thanks!

**Comment by darobin** [comment]
Just to comment on the potential usefulness: there is extensive literature on citation networks (just a few random examples: the [original paper](http://garfield.library.upenn.edu/papers/pricenetworks1965.pdf), [finding missing links and barriers to communication](http://arxiv.org/abs/1511.07643), [showing attention decay over time](http://arxiv.org/abs/1503.01881)). It's slightly different because citation networks can never be cyclic (since published articles typically only reference articles published before them) but the same overall ideas apply. You could find clusters of specifications that are closer (more connected, into communities) than others. You could find circular dependencies. You could identify disconnects between parts of the platform that should be talking, or you could assess the knock-on impact of a spec being broken. You could also make pretty pictures.

I'm not claiming any of those is necessarily particularly useful; just documenting the notion.
