### ISSUE TITLE
Topics for Discussion at Meet-Up

### ISSUE THREAD

**Issue by torgo** [w3ctag/meetings#24]
This is an issue to capture possible topics for discussion at our [developer meet-up on the 1st of February, 2018](https://ti.to/w3c-tag/meet-the-tag-london).

**Comment by LPardue** [comment]
I'd like to talk about the problem space/work of the [HTTPS in Local Network Community Group](https://www.w3.org/community/httpslocal/).

**Comment by rik** [comment]
I'd like to talk about how to make it easier to have accessible rich form controls. Right now, a lot of them are created from scratch because styling forms is very limited and there is not a lot of opportunities for customising their behaviour (think suggestions for `<input>`, autocomplete for `<select>`, date and time widgets). A lot of those form controls have usability or accessibility issues. Is there a plan to improve the situation?

**Comment by torgo** [comment]
@LPardue, @cynthia notes:

https://www.w3.org/wiki/TPAC2016/session-https-local-summary
and
https://www.w3.org/wiki/images/6/6c/TPAC2016_Local_Discovery_and_HTTPS.pdf
