### ISSUE TITLE
Update design review issue template

### ISSUE THREAD

**Issue by cynthia** [w3ctag/meetings#25]

**Comment by dbaron** [comment]
Fixed in:
https://github.com/w3ctag/design-reviews/commit/68a1436aa797b7b30002a5ec39f4ce1dfa451942
https://github.com/w3ctag/design-reviews/commit/b0378d37f14ccbe627d0a099cb351154d5ebf0b8
https://github.com/w3ctag/design-reviews/commit/c98b32a6d8de4fd9f9f5c84192a41f5cd327127b
https://github.com/w3ctag/design-reviews/commit/0f0546e87701681b0215aad5852d87d3baffe832
